import type { Order, UserAccount, AuditLog } from './types';

export const INITIAL_ORDERS: Order[] = [
  {
    _id: '6a7ec0192ef0dd71b931ca31',
    id: 'ORD-889421',
    trackingCode: 'VN-LOG-889421',
    trackingNumber: 'VN-LOG-889421',
    sellerId: '6a7ec0192ef0dd71b931ca00',
    senderName: 'Công ty Dược Phẩm An Bình',
    senderPhone: '0901234567',
    senderAddress: 'Kho Hub Tân Bình, TP. Hồ Chí Minh',
    recipientName: 'Bệnh Viện Đa Khoa Đà Nẵng',
    recipientPhone: '0912345678',
    recipientAddress: 'Hải Châu, Đà Nẵng',
    pickupAddress: {
      fullName: 'Công ty Dược Phẩm An Bình',
      phone: '0901234567',
      address: 'Kho Hub Tân Bình, TP. Hồ Chí Minh',
      ward: 'Tân Bình',
      district: 'Tân Bình',
      province: 'TP. Hồ Chí Minh'
    },
    deliveryAddress: {
      fullName: 'Bệnh Viện Đa Khoa Đà Nẵng',
      phone: '0912345678',
      address: 'Hải Châu, Đà Nẵng',
      ward: 'Hải Châu',
      district: 'Hải Châu',
      province: 'Đà Nẵng'
    },
    items: [{ name: 'Thuốc bảo quản lạnh', quantity: 1, weight: 12.5 }],
    dimensions: { length: 40, width: 30, height: 30 },
    actualWeight: 12.5,
    volumetricWeight: 12.5,
    chargeableWeight: 12.5,
    isCod: false,
    codAmount: 0,
    goodsValue: 10000000,
    baseFee: 480000,
    insuranceFee: 0,
    discountAmount: 0,
    shippingFee: 480000,
    flagFeeWarning: false,
    flagCodAnomaly: false,
    needsManualRouting: false,
    weightKg: 12.5,
    lengthCm: 40,
    widthCm: 30,
    heightCm: 30,
    chargeableWeightKg: 12.5,
    serviceType: 'Chuỗi Lạnh Cold Chain (2-8°C)',
    cost: 480000,
    status: 'IN_TRANSIT',
    originCity: 'TP. Hồ Chí Minh',
    destinationCity: 'Đà Nẵng',
    createdAt: '2026-08-08 14:30',
    updatedAt: '2026-08-08 14:30',
    estimatedDelivery: '2026-08-10 17:00',
    driverName: 'Nguyễn Văn Hùng (Driver 01)',
    events: [
      {
        timestamp: '2026-08-08 14:30',
        location: 'Tân Bình, TP.HCM',
        status: 'CONFIRMED',
        description: 'Tạo đơn thành công từ Kênh Seller',
      },
      {
        timestamp: '2026-08-08 16:15',
        location: 'Kho Hub Tân Bình',
        status: 'PICKED_UP',
        description: 'Tài xế đã nhận kiện hàng bảo quản lạnh',
        actor: 'Nguyễn Văn Hùng',
      },
      {
        timestamp: '2026-08-09 08:00',
        location: 'Quốc Lộ 1A - Tuyến Miền Trung',
        status: 'IN_TRANSIT',
        description: 'Container lạnh GPS đang di chuyển qua Phan Thiết',
        actor: 'Hệ Thống Giám Sát GPS',
      },
    ],
  },
  {
    _id: '6a7ec0192ef0dd71b931ca32',
    id: 'ORD-773102',
    trackingCode: 'VN-LOG-773102',
    trackingNumber: 'VN-LOG-773102',
    sellerId: '6a7ec0192ef0dd71b931ca00',
    senderName: 'Nhà Thuốc Phương Nam',
    senderPhone: '0988776655',
    senderAddress: 'Q. Hoàn Kiếm, Hà Nội',
    recipientName: 'Phòng Khám Minh Anh',
    recipientPhone: '0933221100',
    recipientAddress: 'Q. Ninh Kiều, Cần Thơ',
    pickupAddress: {
      fullName: 'Nhà Thuốc Phương Nam',
      phone: '0988776655',
      address: 'Q. Hoàn Kiếm, Hà Nội',
      ward: 'Hoàn Kiếm',
      district: 'Hoàn Kiếm',
      province: 'Hà Nội'
    },
    deliveryAddress: {
      fullName: 'Phòng Khám Minh Anh',
      phone: '0933221100',
      address: 'Q. Ninh Kiều, Cần Thơ',
      ward: 'Ninh Kiều',
      district: 'Ninh Kiều',
      province: 'Cần Thơ'
    },
    items: [{ name: 'Vật tư y tế', quantity: 1, weight: 3.2 }],
    dimensions: { length: 50, width: 40, height: 20 },
    actualWeight: 3.2,
    volumetricWeight: 8.0,
    chargeableWeight: 8.0,
    isCod: true,
    codAmount: 1500000,
    goodsValue: 1500000,
    baseFee: 320000,
    insuranceFee: 0,
    discountAmount: 0,
    shippingFee: 320000,
    flagFeeWarning: false,
    flagCodAnomaly: false,
    needsManualRouting: false,
    weightKg: 3.2,
    lengthCm: 50,
    widthCm: 40,
    heightCm: 20,
    chargeableWeightKg: 8.0,
    serviceType: 'Vận Chuyển Hỏa Tốc',
    cost: 320000,
    status: 'OUT_FOR_DELIVERY',
    originCity: 'Hà Nội',
    destinationCity: 'Cần Thơ',
    createdAt: '2026-08-07 09:10',
    updatedAt: '2026-08-07 09:10',
    estimatedDelivery: '2026-08-09 18:00',
    driverName: 'Lê Hoàng Nam (Driver 02)',
    events: [
      {
        timestamp: '2026-08-07 09:10',
        location: 'Hà Nội',
        status: 'CONFIRMED',
        description: 'Đơn hàng khởi tạo thành công',
      },
      {
        timestamp: '2026-08-07 11:30',
        location: 'Kho Bắc Hà Nội',
        status: 'PICKED_UP',
        description: 'Đã nhập kho xuất hàng',
      },
      {
        timestamp: '2026-08-08 19:40',
        location: 'Kho Hub Cần Thơ',
        status: 'IN_TRANSIT',
        description: 'Đến kho phân loại miền Tây',
      },
      {
        timestamp: '2026-08-09 13:00',
        location: 'Q. Ninh Kiều, Cần Thơ',
        status: 'OUT_FOR_DELIVERY',
        description: 'Tài xế đang phát hàng tới phòng khám',
        actor: 'Lê Hoàng Nam',
      },
    ],
  },
  {
    _id: '6a7ec0192ef0dd71b931ca33',
    id: 'ORD-991203',
    trackingCode: 'VN-LOG-991203',
    trackingNumber: 'VN-LOG-991203',
    sellerId: '6a7ec0192ef0dd71b931ca00',
    senderName: 'Tập Đoàn Dược Thiết Bị Y Tế',
    senderPhone: '0977112233',
    senderAddress: 'KCN Hiệp Phước, TP.HCM',
    recipientName: 'Bệnh Viện Trung Ương Huế',
    recipientPhone: '0944556677',
    recipientAddress: 'TP. Huế',
    pickupAddress: {
      fullName: 'Tập Đoàn Dược Thiết Bị Y Tế',
      phone: '0977112233',
      address: 'KCN Hiệp Phước, TP.HCM',
      ward: 'Hiệp Phước',
      district: 'Nhà Bè',
      province: 'TP. Hồ Chí Minh'
    },
    deliveryAddress: {
      fullName: 'Bệnh Viện Trung Ương Huế',
      phone: '0944556677',
      address: 'TP. Huế',
      ward: 'Huế',
      district: 'Huế',
      province: 'Thừa Thiên Huế'
    },
    items: [{ name: 'Thiết bị y tế nặng', quantity: 1, weight: 25.0 }],
    dimensions: { length: 60, width: 50, height: 40 },
    actualWeight: 25.0,
    volumetricWeight: 25.0,
    chargeableWeight: 25.0,
    isCod: false,
    codAmount: 0,
    goodsValue: 50000000,
    baseFee: 750000,
    insuranceFee: 0,
    discountAmount: 0,
    shippingFee: 750000,
    flagFeeWarning: false,
    flagCodAnomaly: false,
    needsManualRouting: false,
    weightKg: 25.0,
    lengthCm: 60,
    widthCm: 50,
    heightCm: 40,
    chargeableWeightKg: 25.0,
    serviceType: 'Vận Tải Hàng Nặng Chuẩn',
    cost: 750000,
    status: 'DELIVERED',
    originCity: 'TP. Hồ Chí Minh',
    destinationCity: 'Thừa Thiên Huế',
    createdAt: '2026-08-05 10:00',
    updatedAt: '2026-08-05 10:00',
    estimatedDelivery: '2026-08-07 16:00',
    driverName: 'Phạm Minh Tuấn (Driver 03)',
    events: [
      {
        timestamp: '2026-08-05 10:00',
        location: 'KCN Hiệp Phước',
        status: 'CONFIRMED',
        description: 'Khởi tạo bưu gửi',
      },
      {
        timestamp: '2026-08-07 15:45',
        location: 'TP. Huế',
        status: 'DELIVERED',
        description: 'Khách hàng đã ký nhận POD thành công',
        actor: 'Phạm Minh Tuấn',
      },
    ],
  },
];

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'USR-001',
    email: 'admin@elogistic.vn',
    fullName: 'Nguyễn Văn Quản Lý (Admin Master)',
    phoneNumber: '0909123456',
    role: 'ADMIN',
    isActive: true,
    failedLoginAttempts: 0,
    lastLogin: '2026-08-09 21:15',
  },
  {
    id: 'USR-002',
    email: 'staff.hub@elogistic.vn',
    fullName: 'Trần Thị Thu Hà (Điều Phối Viên Kho Hub)',
    phoneNumber: '0918889999',
    role: 'STAFF',
    isActive: true,
    failedLoginAttempts: 0,
    lastLogin: '2026-08-09 20:45',
  },
  {
    id: 'USR-003',
    email: 'seller@anbinhpharm.com',
    fullName: 'Công Ty Dược An Bình (Seller)',
    phoneNumber: '0901234567',
    role: 'SELLER',
    isActive: true,
    failedLoginAttempts: 0,
    lastLogin: '2026-08-09 18:30',
  },
  {
    id: 'USR-004',
    email: 'hung.driver@elogistic.vn',
    fullName: 'Nguyễn Văn Hùng (Tài Xế Đội Xe 01)',
    phoneNumber: '0912999888',
    role: 'DRIVER',
    isActive: true,
    failedLoginAttempts: 0,
    lastLogin: '2026-08-09 19:10',
  },
  {
    id: 'USR-005',
    email: 'locked.user@gmail.com',
    fullName: 'Trần Văn Khóa (Tài khoản bị tạm khóa)',
    phoneNumber: '0988777666',
    role: 'SELLER',
    isActive: false,
    failedLoginAttempts: 5,
    lastLogin: '2026-08-08 11:20',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'LOG-001',
    action: 'LOGIN_SUCCESS',
    userId: 'USR-001',
    userEmail: 'admin@elogistic.vn',
    ipAddress: '118.69.182.10',
    timestamp: '2026-08-09 21:15:02',
    note: 'Đăng nhập thành công portal Admin qua JWT Access Token',
  },
  {
    id: 'LOG-002',
    action: 'ADMIN_STATUS_CHANGE',
    userId: 'USR-001',
    userEmail: 'admin@elogistic.vn',
    ipAddress: '118.69.182.10',
    timestamp: '2026-08-09 20:30:11',
    note: 'Admin mở khóa tài khoản USR-005 sau khi xác minh thông tin',
  },
  {
    id: 'LOG-003',
    action: 'PASSWORD_CHANGED',
    userId: 'USR-003',
    userEmail: 'seller@anbinhpharm.com',
    ipAddress: '14.161.42.55',
    timestamp: '2026-08-09 18:35:40',
    note: 'Đổi mật khẩu thành công qua quy trình xác thực 6-digit OTP',
  },
  {
    id: 'LOG-004',
    action: 'ORDER_DISPATCHED',
    userId: 'USR-002',
    userEmail: 'staff.hub@elogistic.vn',
    ipAddress: '118.69.182.99',
    timestamp: '2026-08-09 16:20:00',
    note: 'Điều phối viên giao vận đơn VN-LOG-889421 cho tài xế Nguyễn Văn Hùng',
  },
];
